### ISSUE TITLE
area combination fails when fixing contour plot

### ISSUE THREAD

**Issue by kzhooou** [Conclusio/matlab-epsclean#11]
brilliant script for fixing annoying white lines 
but not working when I tried to fix the artifacts between areas (MatlabR2017a)

**Comment by Conclusio** [comment]
Could you please provide an example .eps file for your issue? I.e. the input file before calling 'epsclean'.
Otherwise I cannot really reproduce the problem.

Thank you.

**Comment by kzhooou** [comment]
[Original.zip](https://github.com/Conclusio/matlab-epsclean/files/1894309/Original.zip)
Please see attached the original eps. Thanks ever so much that your script already helped a lot without the area combination

**Comment by Conclusio** [comment]
Thank you for the input.
I cleaned your file with R2016b [cleaned.zip](https://github.com/Conclusio/matlab-epsclean/files/1894337/cleaned.zip).
Please check if that is the expected result.

As of now, I do not have access to another Matlab version.
What exactly happens in your MatlabR2017a version?
No file created?
Broken file created?
Artifacts remain?

**Comment by kzhooou** [comment]
This is the same as what I've got from the combination option being set 'false', while the gaps between areas of different colours remain.
![image](https://user-images.githubusercontent.com/38227689/38556022-18bfe056-3cc0-11e8-89e6-ad3984276b20.png)

Or maybe do I misunderstand the effect of the option to combine areas?

**Comment by kzhooou** [comment]
with 'combineAreas',true, it ran for 9010.899407 seconds and generated a broken file

**Comment by Conclusio** [comment]
I see...
So, combineAreas combines only areas of equal colors/properties. That means the lines between different shaded areas will not disappear. But, I have a [solution for you](https://github.com/altmany/export_fig/issues/44#issuecomment-339084805).

In the "cleaned" file, change line 
/f/fill ld
to
/f{GS 1 LW S GR fill}bd
and move it below the /LW... line

This eliminates the lines (at least in my viewer).
I will add this fix to my script soon, because it is a simple fix.

combineAreas can be left to 'false' in your case.
Sorry about the runtime by the way, it really isn't much optimized for speed.

**Comment by kzhooou** [comment]
No worries on the speed it's good enough.

Small spikes appear when I did so
![image](https://user-images.githubusercontent.com/38227689/38557860-498e5dec-3cc6-11e8-8f56-827c6c14fb9e.png)
But I've found alternative way to make gaps less obvious using inkscape

Another small bug I experience is that the code does not always capture white filled areas, see below
![image](https://user-images.githubusercontent.com/38227689/38558131-1af035f4-3cc7-11e8-80f7-c80fe6019483.png)
[Original_filledwhite.zip](https://github.com/Conclusio/matlab-epsclean/files/1894656/Original_filledwhite.zip)

highlighted are areas I fill white to cover the plot outside the boundary

**Comment by Conclusio** [comment]
Regarding the spikes: That's a shame, then the workaround needs improvement...
Regarding white filled areas: That's a Z-order problem. Use: epsclean(...  ,  'groupSoft',true); to handle that.

**Comment by kzhooou** [comment]
It works! Thanks again for your help!

**Comment by Conclusio** [comment]
You're welcome.

On last time, regarding the spikes again:
You can eliminate them with choosing this statement instead:
/f{GS 0.01 LW S GR fill}bd

So the value 1 is changed to 0.01. What this statement in general does is drawing an additional polyline with the given width (0.01) around every area, basically eliminating gaps between areas.

**Comment by kzhooou** [comment]
It works perfectly! Cheers!!

**Comment by jbkajtar** [comment]
Brilliant! Editing that statement solved my problems too! Thank you!
