### ISSUE TITLE
Possible incompatibility with 2016a

### ISSUE THREAD

**Issue by giulianobernardi** [Conclusio/matlab-epsclean#5]
Hello,  I tried your script with Matlab 2016a and it doesn't seem to work, as it outputs something like this

![bad_exp](https://cloud.githubusercontent.com/assets/16898589/24861624/bd99540e-1df9-11e7-87ee-b5db96a9f013.png)

Do you think it's really a version problem or might it be due to something else?

**Comment by Conclusio** [comment]
Thank you. I messed up with my last commit. Please try again with the current version and report any changes.

**Comment by giulianobernardi** [comment]
Now the code you posted in the release page works!

However, FYI, I tried to use it for the specific case I needed it for (saving a clean spectrogram), and it's still not working properly.
Here's a dummy example:
`load handel.mat
spectrogram(y,128,120,128,Fs)
print(gcf,'-depsc','-painters','out.eps');
epsclean('out.eps','clean.eps');`

Anyway, thanks for your help. At least, contour plots seems to be working now.

[out.pdf](https://github.com/Conclusio/matlab-epsclean/files/915955/out.pdf)
[clean.pdf](https://github.com/Conclusio/matlab-epsclean/files/915954/clean.pdf)

**Comment by Conclusio** [comment]
Can replicate this behavior in 2016b, so it's a bit off-topic, but I will look into this issue. Will come back to you if I am able to fix this.

**Comment by giulianobernardi** [comment]
Yeah, I agree it's off topic. 
I just wanted to mention it cause I guess I will not loose too much time anymore trying to bypass this graphical problems in Matlab, but still wanted to point it out ;)

**Comment by Conclusio** [comment]
I rewrote the script to include your case and tried to be as general as possible. With the committed changes it looks more or less correct, but introduces a different z-ordering between the elements, which causes the color bar on the right to have some lines behind the color bar. So, it is not perfect and I created an issue for it (#6).

This issue is closed for now.
