### ISSUE TITLE
Apparent bug

### ISSUE THREAD

**Issue by jmarkow** [Conclusio/matlab-epsclean#7]
Nice work, such a useful script!  I kept getting the following error with my eps files,

```
Error using containers.Map/subsasgn
Specified key type does not match the type expected for this
container.

Error in epsclean>getBlockData (line 377)
        blockMap(blockId) = s; %#ok<NASGU>

Error in epsclean (line 203)
            [cbNewBlock,cbConn] =
            getBlockData(blockMap,cbPrefix);
```

I did a little hunting and found that `blockId` was occassionally set to `[]`, so I added the following check to the functions `writeBlocks` and `getBlockdata`

```
if isempty(blockId)
  blockId='';
end
```

Everything seems to work now.  Tested with MATLAB 2016a and 2017a.

**Comment by Conclusio** [comment]
Thank you for your time.
I tried to fix it in a different way, but it should still work. I don't have a test case though.
Changes are committed. I would appreciate it if you could test it or provide a sample eps file for me to test it.

**Comment by jmarkow** [comment]
I'll test today and let you know if it works.  Appreciate the fast response!

**Comment by Conclusio** [comment]
I assume it is fixed and close this issue.

**Comment by jmarkow** [comment]
Sorry for taking so long to respond, yes it's fixed.
