### ISSUE TITLE
Issue with black backgrounds

### ISSUE THREAD

**Issue by jmarkow** [Conclusio/matlab-epsclean#8]
Looks like the script does not respect the `InvertHardCopy` option `set(gcf,'InvertHardCopy','off')` which allows one to save figures with black backgrounds.  All my figures with black backgrounds revert to white backgrounds after running this script.

**Comment by Conclusio** [comment]
Thank you for your comment.
I'm not certain I can reproduce the problem. Does `epsclean('input.eps','output.eps',false,true);` resolve your issue?

If not, is it possible for you to share the eps file or code for generating it?

**Comment by jmarkow** [comment]
I'll give that a shot and report back.

**Comment by jmarkow** [comment]
I haven't seen the problem since using the syntax you recommended.  I think you can consider this fixed for now.
